# Generated by Django 2.2.5 on 2019-09-05 13:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('qtd', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('client', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('address', models.CharField(max_length=400)),
                ('sender', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Pendente de envio', 'Pendente de envio'), ('Enviado', 'Enviado'), ('Entregue', 'Entregue')], default='Pendente de envio', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('qtd', models.PositiveIntegerField()),
            ],
        ),
    ]
